/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterpretePanel.java
 *
 * Created on 04-dic-2009, 20:51:58
 */

package interfaz.interprete;

import interprete.InstruccionPila;
import interprete.LectorBytecode;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;

/**
 *
 * @author golthiryus
 */
public class InterpretePanel extends javax.swing.JPanel {

    /** Creates new form InterpretePanel */
    public InterpretePanel() {
        initComponents();
    }

    public void decompilar(File f, LectorBytecode lb) throws IOException {
        if(f == null || !f.canRead())
            throw new IOException("Archivo inválido o ilegible");

        ArrayList<InstruccionPila> programa = lb.leerFuente(f);
        for(Iterator<InstruccionPila> it = programa.iterator(); it.hasNext();) {
            InstruccionPila ins = it.next();
            textArea.append(ins.toString());
            if(ins.getDato() != null)
                textArea.append(" "+ins.getDato().toString());
            textArea.append("\n");
        }
    }

    public void compilar(File f) {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesPanel = new javax.swing.JPanel();
        decompilarBot = new javax.swing.JButton();
        compilarBot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        botonesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        decompilarBot.setText("Decompilar...");
        decompilarBot.setToolTipText("Al decompilar un archivo en bytecode este\nse mostrará como cadenas alfanumericas");
        decompilarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decompilarBotActionPerformed(evt);
            }
        });

        compilarBot.setText("Compilar...");
        compilarBot.setToolTipText("Al compilar, el texto escrito sera traducido a lenguaje \nde pila, siempre y cuando su sintáxis sea correcta");

        javax.swing.GroupLayout botonesPanelLayout = new javax.swing.GroupLayout(botonesPanel);
        botonesPanel.setLayout(botonesPanelLayout);
        botonesPanelLayout.setHorizontalGroup(
            botonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, botonesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(decompilarBot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 194, Short.MAX_VALUE)
                .addComponent(compilarBot)
                .addContainerGap())
        );
        botonesPanelLayout.setVerticalGroup(
            botonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(botonesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(compilarBot)
                .addComponent(decompilarBot))
        );

        add(botonesPanel, java.awt.BorderLayout.PAGE_END);

        textArea.setColumns(20);
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setText("Este panel hace de intermediario entre el bytecode del lenguaje a pila y el explicado en clase (con sentencias alfanumericas como \"apila 3\" o \"suma\").\n\nAl decompilar un archivo en bytecode este se mostrará como cadenas alfanumericas\n\nAl compilar, el texto escrito sera traducido a lenguaje de pila, siempre y cuando su sintáxis sea correcta");
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void decompilarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decompilarBotActionPerformed

    }//GEN-LAST:event_decompilarBotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel botonesPanel;
    private javax.swing.JButton compilarBot;
    private javax.swing.JButton decompilarBot;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables

}
