/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompiladorFrame.java
 *
 * Created on 25-ene-2010, 17:33:22
 */
package interfaz.compilador;

import compilador.lexico.AnalizadorLexico;
import compilador.lexico.Tokens.Token;
import compilador.traductor.TraductorCodP;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.PipedReader;
import java.io.PipedWriter;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import pila.interprete.EscritorPila;
import pila.interprete.Interprete;
import pila.interprete.instrucciones.InstruccionInterprete;

/**
 *
 * @author usuario_local
 */
public class CompiladorFrame extends javax.swing.JFrame {

    File inputFile;
    PipedWriter pWriter = new PipedWriter();

    /** Creates new form CompiladorFrame */
    public CompiladorFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaEntrada = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDebug = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaEjecucion = new javax.swing.JTextArea();
        compilarButton = new javax.swing.JButton();
        ejecutarButton = new javax.swing.JButton();
        abrirButton = new javax.swing.JButton();
        inputTextField = new javax.swing.JTextField();
        EnviarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaEntrada.setColumns(20);
        textAreaEntrada.setEditable(false);
        textAreaEntrada.setRows(5);
        textAreaEntrada.setName("EntradaCodigo"); // NOI18N
        jScrollPane1.setViewportView(textAreaEntrada);

        textAreaDebug.setColumns(20);
        textAreaDebug.setEditable(false);
        textAreaDebug.setRows(5);
        textAreaDebug.setName("ConsolaCompilacion"); // NOI18N
        jScrollPane2.setViewportView(textAreaDebug);

        textAreaEjecucion.setColumns(20);
        textAreaEjecucion.setRows(5);
        textAreaEjecucion.setName("ConsolaEjecucion"); // NOI18N
        jScrollPane3.setViewportView(textAreaEjecucion);

        compilarButton.setText("Compilar");
        compilarButton.setName("CompilarButton"); // NOI18N
        compilarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                compilarButtonMouseClicked(evt);
            }
        });

        ejecutarButton.setText("Ejecutar");
        ejecutarButton.setName("EjecutarButton"); // NOI18N
        ejecutarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ejecutarButtonMouseClicked(evt);
            }
        });

        abrirButton.setText("Abrir");
        abrirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirButtonMouseClicked(evt);
            }
        });

        EnviarButton.setText("Enviar");
        EnviarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EnviarButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ejecutarButton)
                                    .addComponent(compilarButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(abrirButton)
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 638, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 565, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(EnviarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(abrirButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(compilarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ejecutarButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EnviarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Writes everything into the text area. */
    private class TextAreaOutputStream extends java.io.OutputStream {

        @Override
        public void write(int b) throws java.io.IOException {
            String s = new String(new char[]{(char) b});
            textAreaEjecucion.append(s);
        }
    }

    private void ejecutarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ejecutarButtonMouseClicked
        try {
            System.setOut(new PrintStream(new TextAreaOutputStream()));
            PipedReader pReader = new PipedReader(pWriter);
            InputStreamReader reader = new InputStreamReader(new FileInputStream(inputFile));
            AnalizadorLexico al = new AnalizadorLexico(reader);
            ArrayList<Token> tokens = al.getArrayTokens();
            imprimirTokens(tokens);
            TraductorCodP tcodp = new TraductorCodP(tokens);
            ArrayList<InstruccionInterprete> ai = tcodp.traducir();
            imprimir(ai);
            File f = new File("./codigo_binario");
            EscritorPila ep = new EscritorPila();
            ep.escribirPrograma(ai, f);
            Interprete interprete = new Interprete(false, pReader, new PrintWriter(System.out,true));
            File f2 = new File("./codigo_binario");
            interprete.leerPrograma(f2);
            interprete.ejecutarPrograma();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        } finally {
            //System.exit(0);
        }
}//GEN-LAST:event_ejecutarButtonMouseClicked

    private void abrirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_abrirButtonMouseClicked
        try {
            inputFile = new File(abrirFich());
            InputStreamReader reader = new InputStreamReader(new FileInputStream(inputFile));
            this.textAreaEntrada.read(reader, evt);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
}//GEN-LAST:event_abrirButtonMouseClicked

    private void compilarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_compilarButtonMouseClicked
//JOptionPane.showInputDialog(evt)        // TODO add your handling code here:
}//GEN-LAST:event_compilarButtonMouseClicked

    private void EnviarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EnviarButtonMouseClicked
        try {
            inputTextField.write(pWriter);
            inputTextField.setText("");
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_EnviarButtonMouseClicked

    private void imprimirTokens(ArrayList<Token> tokens) {
        Iterator<Token> it = tokens.iterator();
        while (it.hasNext()) {
            System.out.println(it.next());
        }

    }

    private void imprimir(ArrayList<InstruccionInterprete> ai) {
        Iterator<InstruccionInterprete> it = ai.iterator();
        while (it.hasNext()) {
            System.out.println(it.next());
        }

    }

    private String abrirFich() {
        JFileChooser selectFich = new JFileChooser();
        selectFich.setEnabled(true);
        selectFich.setCurrentDirectory(new File("./src/compilador/traductor"));
        selectFich.showOpenDialog(this);
        return selectFich.getSelectedFile().getAbsolutePath();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CompiladorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EnviarButton;
    private javax.swing.JButton abrirButton;
    private javax.swing.JButton compilarButton;
    private javax.swing.JButton ejecutarButton;
    private javax.swing.JTextField inputTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea textAreaDebug;
    private javax.swing.JTextArea textAreaEjecucion;
    protected javax.swing.JTextArea textAreaEntrada;
    // End of variables declaration//GEN-END:variables
}
