/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * InterpretePanel.java
 *
 * Created on 21-ene-2010, 21:07:45
 * @author GRUPO 3: Gonzalo Ortiz Jaureguizar, Alicia Perez Jimenez, Laura Reyero Sainz, Hector Sanjuan Redondo, Ruben Tarancon Garijo
 */

package interfaz;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pila.Instruccion;
import pila.interprete.Interprete;
import pila.interprete.LectorPila;
import pila.interprete.excepiones.InstruccionExc;
import pila.interprete.excepiones.LectorExc;

/**
 *
 * @author golthiryus
 */
public class InterpretePanel extends javax.swing.JPanel {

    File objetoFile;
    Interprete interprete;
    ConsolaInputStream entrada;
    ConsolaOutpuStream salida;


    private class ConsolaInputStream extends InputStream {

        @Override
        public int read() throws IOException {
            throw new UnsupportedOperationException("Not supported yet.");
        }
        
    };

    private class ConsolaOutpuStream extends OutputStream {
        int b1 = 0;
        @Override
        public void write(int b) throws IOException {
            if((b & 0x80)==0)
                consolaText.append(Character.toString((char)(b&0x7F)));
            else
                if(b1 != 0) {
                    b = ((b1 & 0x1f) << 6) + (b & 0x3f);
                    consolaText.append(Character.toString((char)b));
                    b1 =0;
                }
                else
                    b1 = b;
        }
    };

    /** Creates new form InterpretePanel */
    public InterpretePanel() {
        initComponents();
        entrada = new ConsolaInputStream();
        salida = new ConsolaOutpuStream();
    }

    public void setFile(File f, boolean depuracion) throws IOException, FileNotFoundException {
        try {
            bytecodeText.setText("");
            consolaText.setText("");

            this.objetoFile = f;
            LectorPila lector = new LectorPila();

            ArrayList<Instruccion> programa = lector.leerPrograma(f);
            for(int i = 0; i < programa.size();i++)
                bytecodeText.append(programa.get(i).toString());
        } catch (LectorExc ex) {
           JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error en el bytecode", JOptionPane.ERROR_MESSAGE);
        }
        
    }

    public void ejecutar(boolean depuracion) throws IOException, FileNotFoundException {
        try {
            interprete = new Interprete(depuracion,entrada,new PrintWriter(salida));
            interprete.leerPrograma(objetoFile);
            interprete.ejecutarPrograma();
        } catch (LectorExc ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error en el bytecode", JOptionPane.ERROR_MESSAGE);
        } catch (InstruccionExc ex) {
            JOptionPane.showMessageDialog(this, ex.getLocalizedMessage(), "Error en ejecución", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entradaFiel = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        bytecodeText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        consolaText = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        entradaFiel.setText("Entrada");
        add(entradaFiel, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        bytecodeText.setColumns(20);
        bytecodeText.setEditable(false);
        bytecodeText.setRows(5);
        jScrollPane1.setViewportView(bytecodeText);

        jPanel1.add(jScrollPane1);

        consolaText.setColumns(20);
        consolaText.setEditable(false);
        consolaText.setRows(5);
        jScrollPane2.setViewportView(consolaText);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea bytecodeText;
    private javax.swing.JTextArea consolaText;
    private javax.swing.JTextField entradaFiel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
