/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CompiladorPanel.java
 *
 * Created on 21-ene-2010, 13:31:53
 * @author GRUPO 3: Gonzalo Ortiz Jaureguizar, Alicia Perez Jimenez, Laura Reyero Sainz, Hector Sanjuan Redondo, Ruben Tarancon Garijo
 */

package interfaz;

import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import pila.Instruccion;
import pila.interprete.EscritorPila;

/**
 *
 * @author golthiryus
 */
public class CompiladorPanel extends javax.swing.JPanel {

    File fuenteFile, objetoFile;

    /** Creates new form CompiladorPanel */
    public CompiladorPanel() {
        initComponents();
        fuenteFile = null;
        objetoFile = null;
    }

    public void abrirFuente() throws IOException {
        fuenteText.read(new FileReader(fuenteFile), null); //TODO: mirar javadoc
    }

    public void guardar() throws IOException {
        fuenteText.write(new FileWriter(fuenteFile));
    }

    public void compilar() throws Exception {
        ArrayList<Instruccion> programa = null;
        //TODO: obtener el programa
        EscritorPila escritor = new EscritorPila();
        escritor.escribirPrograma(programa, objetoFile);
        abrirObjeto();
    }

    public void abrirObjeto() throws IOException {
        FileReader reader = new FileReader(objetoFile);
        objetoText.read(reader, null); //TODO: mirar javadoc
    }

    public void ejecutar() {
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        abrirBot = new javax.swing.JButton();
        guardarBot = new javax.swing.JButton();
        compilarBot = new javax.swing.JButton();
        ejecutarBot = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fuenteText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        objetoText = new javax.swing.JTextArea();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        abrirBot.setText("Abrir...");
        abrirBot.setFocusable(false);
        abrirBot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        abrirBot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(abrirBot);

        guardarBot.setText("Guardar...");
        guardarBot.setFocusable(false);
        guardarBot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardarBot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(guardarBot);

        compilarBot.setText("Compilar...");
        compilarBot.setFocusable(false);
        compilarBot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        compilarBot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(compilarBot);

        ejecutarBot.setText("Ejecutar");
        ejecutarBot.setEnabled(false);
        ejecutarBot.setFocusable(false);
        ejecutarBot.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ejecutarBot.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(ejecutarBot);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        fuenteText.setColumns(20);
        fuenteText.setRows(5);
        jScrollPane1.setViewportView(fuenteText);

        jPanel1.add(jScrollPane1);

        objetoText.setColumns(20);
        objetoText.setEditable(false);
        objetoText.setRows(5);
        objetoText.setEnabled(false);
        jScrollPane2.setViewportView(objetoText);

        jPanel1.add(jScrollPane2);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirBot;
    private javax.swing.JButton compilarBot;
    private javax.swing.JButton ejecutarBot;
    private javax.swing.JTextArea fuenteText;
    private javax.swing.JButton guardarBot;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextArea objetoText;
    // End of variables declaration//GEN-END:variables

}
